# Generated by Django 3.0.3 on 2020-05-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomtache', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('debut', models.DateTimeField()),
                ('fin', models.DateTimeField()),
            ],
        ),
    ]
